
version: '3.8'

networks:
  fin-network:
    driver: bridge
    external: true


services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD} # Set the root password
    volumes:
      - ./docker/mongo_data:/data/db
    networks:
      - fin-network
  app:
    image: my-go-app
    volumes:
      - .:/home
      - .env:/usr/local/.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-processing-app
    ports:
      - "50052:50052"
    depends_on:
      - db
    links:
      - db
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}ва
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - fin-network

