
version: '3'

tasks:
  proto:
    desc: "Generate Go code from Protobuf files"
    cmds:
      -  protoc -I ./api/grpc --go_out=pkg/grpc --go_opt=paths=source_relative --go-grpc_out=pkg/grpc --go-grpc_opt=paths=source_relative api/grpc/*.proto
