
version: '3'

tasks:
  proto:
    desc: "Generate Go code from Protobuf files"
    cmds:
      - protoc -I ./api/grpc --go_out=pkg/grpc --go_opt=paths=source_relative --go-grpc_out=pkg/grpc --go-grpc_opt=paths=source_relative api/grpc/*.proto
  migrateCreate:
    desc: "Create migration files"
    cmds:
      - goose -dir=db/migrations create {{ .name }} sql
  migrateUp:
    cmds:
      - source .env && goose -dir=db/migrations postgres "postgres://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?sslmode=disable" up
  migrateDown:
    cmds:
      - source .env && goose -dir=db/migrations postgres "postgres://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?sslmode=disable" down
  migrateStatus:
    cmds:
      - source .env && goose -dir=db/migrations postgres "postgres://$POSTGRES_USERNAME:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DATABASE?sslmode=disable" status
  vet:
    go vet ./...
  lint:
    golangci-lint run ./...
