// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: targets.proto

package grpc_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TargetsService_GetTargets_FullMethodName = "/TargetsService/GetTargets"
)

// TargetsServiceClient is the client API for TargetsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Получение целей сервисом обработки
type TargetsServiceClient interface {
	GetTargets(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*TargetResponse, error)
}

type targetsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTargetsServiceClient(cc grpc.ClientConnInterface) TargetsServiceClient {
	return &targetsServiceClient{cc}
}

func (c *targetsServiceClient) GetTargets(ctx context.Context, in *TargetRequest, opts ...grpc.CallOption) (*TargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TargetResponse)
	err := c.cc.Invoke(ctx, TargetsService_GetTargets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TargetsServiceServer is the server API for TargetsService service.
// All implementations must embed UnimplementedTargetsServiceServer
// for forward compatibility.
//
// Получение целей сервисом обработки
type TargetsServiceServer interface {
	GetTargets(context.Context, *TargetRequest) (*TargetResponse, error)
	mustEmbedUnimplementedTargetsServiceServer()
}

// UnimplementedTargetsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTargetsServiceServer struct{}

func (UnimplementedTargetsServiceServer) GetTargets(context.Context, *TargetRequest) (*TargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTargets not implemented")
}
func (UnimplementedTargetsServiceServer) mustEmbedUnimplementedTargetsServiceServer() {}
func (UnimplementedTargetsServiceServer) testEmbeddedByValue()                        {}

// UnsafeTargetsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TargetsServiceServer will
// result in compilation errors.
type UnsafeTargetsServiceServer interface {
	mustEmbedUnimplementedTargetsServiceServer()
}

func RegisterTargetsServiceServer(s grpc.ServiceRegistrar, srv TargetsServiceServer) {
	// If the following call pancis, it indicates UnimplementedTargetsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TargetsService_ServiceDesc, srv)
}

func _TargetsService_GetTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TargetsServiceServer).GetTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TargetsService_GetTargets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TargetsServiceServer).GetTargets(ctx, req.(*TargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TargetsService_ServiceDesc is the grpc.ServiceDesc for TargetsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TargetsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "TargetsService",
	HandlerType: (*TargetsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTargets",
			Handler:    _TargetsService_GetTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "targets.proto",
}
