// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: tickers.proto

package grpc_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TickersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TickersRequest) Reset() {
	*x = TickersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tickers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickersRequest) ProtoMessage() {}

func (x *TickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tickers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickersRequest.ProtoReflect.Descriptor instead.
func (*TickersRequest) Descriptor() ([]byte, []int) {
	return file_tickers_proto_rawDescGZIP(), []int{0}
}

type TickersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ticker    string `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Shortname string `protobuf:"bytes,2,opt,name=shortname,proto3" json:"shortname,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Exists    bool   `protobuf:"varint,4,opt,name=exists,proto3" json:"exists,omitempty"`
}

func (x *TickersResponse) Reset() {
	*x = TickersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tickers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickersResponse) ProtoMessage() {}

func (x *TickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickersResponse.ProtoReflect.Descriptor instead.
func (*TickersResponse) Descriptor() ([]byte, []int) {
	return file_tickers_proto_rawDescGZIP(), []int{1}
}

func (x *TickersResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *TickersResponse) GetShortname() string {
	if x != nil {
		return x.Shortname
	}
	return ""
}

func (x *TickersResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TickersResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type MultipleTickerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tickers []*TickersResponse `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"` // Массив
}

func (x *MultipleTickerResponse) Reset() {
	*x = MultipleTickerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tickers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultipleTickerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleTickerResponse) ProtoMessage() {}

func (x *MultipleTickerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tickers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleTickerResponse.ProtoReflect.Descriptor instead.
func (*MultipleTickerResponse) Descriptor() ([]byte, []int) {
	return file_tickers_proto_rawDescGZIP(), []int{2}
}

func (x *MultipleTickerResponse) GetTickers() []*TickersResponse {
	if x != nil {
		return x.Tickers
	}
	return nil
}

var File_tickers_proto protoreflect.FileDescriptor

var file_tickers_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x10, 0x0a, 0x0e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x73, 0x0a, 0x0f, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x65, 0x78, 0x69, 0x73, 0x74, 0x73, 0x22, 0x44, 0x0a, 0x16, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70,
	0x6c, 0x65, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x07, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x32, 0x50, 0x0a, 0x0e,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x54, 0x69, 0x63,
	0x6b, 0x65, 0x72, 0x73, 0x12, 0x0f, 0x2e, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0f,
	0x5a, 0x0d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tickers_proto_rawDescOnce sync.Once
	file_tickers_proto_rawDescData = file_tickers_proto_rawDesc
)

func file_tickers_proto_rawDescGZIP() []byte {
	file_tickers_proto_rawDescOnce.Do(func() {
		file_tickers_proto_rawDescData = protoimpl.X.CompressGZIP(file_tickers_proto_rawDescData)
	})
	return file_tickers_proto_rawDescData
}

var file_tickers_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tickers_proto_goTypes = []any{
	(*TickersRequest)(nil),         // 0: TickersRequest
	(*TickersResponse)(nil),        // 1: TickersResponse
	(*MultipleTickerResponse)(nil), // 2: MultipleTickerResponse
}
var file_tickers_proto_depIdxs = []int32{
	1, // 0: MultipleTickerResponse.tickers:type_name -> TickersResponse
	0, // 1: TickersService.GetMultipleTickers:input_type -> TickersRequest
	2, // 2: TickersService.GetMultipleTickers:output_type -> MultipleTickerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tickers_proto_init() }
func file_tickers_proto_init() {
	if File_tickers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tickers_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TickersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tickers_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TickersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tickers_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*MultipleTickerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tickers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tickers_proto_goTypes,
		DependencyIndexes: file_tickers_proto_depIdxs,
		MessageInfos:      file_tickers_proto_msgTypes,
	}.Build()
	File_tickers_proto = out.File
	file_tickers_proto_rawDesc = nil
	file_tickers_proto_goTypes = nil
	file_tickers_proto_depIdxs = nil
}
